"""Paper content: Section 3.8 extended evaluation (real figures fig6-fig10) + ranked-gene table."""
import os, sys
import numpy as np, pandas as pd
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_paper import P, H1, H2, BODY, fig, tbl, ROOT, PageBreak
from reportlab.lib.units import inch


def story_ext(story, R):
    F = lambda n: os.path.join(ROOT, 'figures', n)
    al = pd.read_csv(os.path.join(ROOT, 'results', 'aligned_predictions_all_models.csv'))
    al = al.merge(pd.read_csv(os.path.join(ROOT, 'results', 'ensemble_oof.csv'))[['bnumber', 'ensemble']], on='bnumber')
    y = al.essential.values
    pk = {}
    for c in ['fba_min', 'gnn', 'cnn', 'kmer', 'ensemble']:
        o = np.argsort(-al[c].values, kind='stable')
        pk[c] = [y[o[:k]].mean() for k in (25, 50, 100, 200)]
    story += [PageBreak(), P('Appendix D. Extended evaluation: distributions, calibration and early precision', H1),
              P('AUROC summarizes the whole ranking, but a biologist using a virtual cell reads it from the '
                'top: which genes should be tested first? This section reports the views of the same out-of-fold '
                'scores that answer that question. Every panel is generated by scripts/make_figures_ext.py '
                'directly from results/aligned_predictions_all_models.csv and results/ensemble_oof.csv; no number '
                'is transcribed by hand.', BODY)]
    story += fig(F('fig6_score_distributions.png'), 6.3 * inch,
                 'Figure 6. Out-of-fold score distributions by Gerdes class for the GCN, sequence CNN, k-mer baseline '
                 'and stacked ensemble. Only the ensemble develops a distinct high-score essential mode (scores &gt; 0.8).')
    story += [P('Figure 6 shows why the ensemble beats every member on ranking. Each learned base model shifts the '
                'essential class to the right but leaves the two classes overlapping across the full score range. The '
                'ensemble, which also receives the binary FBA calls, splits the essential genes into two groups: a '
                'sharp mode near 0.85-0.95 made of genes that FBA calls essential AND the learned models score high, '
                'and a broad low mode of essential genes that FBA misses. The second group is the ceiling of this '
                'architecture - no amount of stacking recovers genes that none of the inputs can see.', BODY)]
    story += fig(F('fig10_precision_at_k.png'), 4.8 * inch,
                 'Figure 10. Precision among the top-k ranked genes. Dotted line: prevalence (0.172).')
    rows = [['model', 'P@25', 'P@50', 'P@100', 'P@200']] + [[c] + [f'{v:.2f}' for v in pk[c]] for c in pk]
    story += tbl(rows, 'Table 8. Precision at k (fraction of the top-k genes that are essential in Gerdes 2003).',
                 widths=[1.3 * inch] + [0.9 * inch] * 4)
    story += [P(f'At k = 50 the ensemble reaches precision {pk["ensemble"][1]:.2f}, {pk["ensemble"][1]/y.mean():.1f}x the '
                f'prevalence and well above the best single model (FBA minimal {pk["fba_min"][1]:.2f}, GCN '
                f'{pk["gnn"][1]:.2f}). The advantage shrinks with k: by k = 200 the ensemble ({pk["ensemble"][3]:.2f}) is only '
                f'marginally ahead of FBA ({pk["fba_min"][3]:.2f}). The practical reading is that the ensemble is a good '
                'triage tool for the first 50-100 experiments and not a replacement for FBA deeper in the list. The '
                'early dip in the ensemble curve at k = 10 is real and explained in Section 4: the very top of the '
                'ranking is occupied by molybdopterin genes (moaD, moaE, mobA, moaC) that every component scores as '
                'essential and that Gerdes finds dispensable - the biomass-objective artifact analysed in Section 4.3.', BODY)]
    story += fig(F('fig7_calibration.png'), 4.2 * inch,
                 'Figure 7. Reliability diagram (quantile bins; scores min-max scaled per model).')
    story += [P('Figure 7 shows that none of the scores is calibrated as a probability: all curves lie below the '
                'diagonal, meaning that scaled scores overstate essentiality. This is expected for class-weighted '
                'training (Appendix C, eq. C16), which trades calibration for balanced error. The ensemble curve is '
                'the closest to monotone and reaches an observed essential fraction of about 0.55 in its top decile. '
                'For downstream use as probabilities, a Platt or isotonic recalibration on a held-out split is required; '
                'we do not claim calibrated probabilities anywhere in this paper.', BODY)]
    story += fig(F('fig8_fold_auroc.png'), 4.4 * inch,
                 'Figure 8. Per-fold AUROC for the GCN and the sequence CNN (3-fold stratified CV).')
    story += [P('Fold-to-fold spread (Figure 8) is about 0.05 AUROC for the GCN and 0.02 for the CNN. The GCN spread '
                'is comparable to the gap between the GCN and FBA, so the ordering GCN &gt; FBA-rich in Table 1 '
                'should be read as a tie within fold noise. The ensemble gain (+0.057 over FBA minimal) is larger '
                'than both spreads in this historical comparison, but rescaling and the later score-lineage audit limit causal and hard-call inference.', BODY)]
    story += fig(F('fig9_threshold.png'), 4.4 * inch,
                 'Figure 9. F1 and number of predicted essential genes versus the growth-fraction threshold.')
    story += [P('Figure 9 is the graphical form of the bimodality result (eq. C23): both curves are flat, since exactly '
                '183 genes are called essential at 0.5%, 1% and 5% of wild-type growth.', BODY)]
    top = al.sort_values('ensemble', ascending=False).head(40)
    rows = [['rank', 'b-number', 'gene', 'ensemble', 'FBA min', 'GCN', 'Gerdes']]
    for i, (_, r) in enumerate(top.iterrows(), 1):
        rows.append([str(i), r.bnumber, r.gene_name, f'{r.ensemble:.3f}', 'E' if r.fba_min > .5 else '-',
                     f'{r.gnn:.2f}', 'essential' if r.essential else 'non-ess.'])
    story += [P('Table 9 lists the 40 highest-ranked genes so that any reader can check the ranking against '
                'EcoCyc or their own data. False positives cluster in cofactor biosynthesis (molybdopterin, folate), '
                'which motivated the provenance audit of Section 4.4.', BODY)]
    story += tbl(rows, 'Table 9. Top 40 genes by out-of-fold ensemble score with the Gerdes 2003 call.')
    return story
