"""Main-body 2026 calibration and structural-discovery updates, preserving the locked failure."""
import json,os
from build_paper import P,H1,H2,BODY,EQ,tbl,fig,ROOT,PageBreak

def story_calibration(story,R):
    bg=R('bigg_model_survey.json'); census=R('bigg_moco_growth_summary.json');c=R('calibration_gate.json');a=R('calibration_lineage_audit.json'); second=R('bigg_second_family_verification.json'); rv=R('rousset_validation.json'); gd=R('rousset_genomic_dependence_audit.json'); mn=R('moco_specificity_null_ijn1463.json'); topo=R('biomass_topology_manifest.json'); ts=R('biomass_topology_exploratory.json')
    assert census['scorable']==68 and census['models_with_at_least_one_flip']==63
    assert c['verdict']['first_passing_rung'] is None and len(c['ladder'])==5
    story += [PageBreak(),P('7. Later locked studies and audit of the calibration claim',H1),
              P('7.1 BiGG census: distinguishing model structure from biology',H2),
              P(f"The BiGG v2 listing supplied {bg['listed']} unique model accessions, each downloaded and hashed. "
                f"Of these, {len(bg['moco_biomass_models'])} have a positive-weight biomass objective consuming a MoCo-named "
                "compound; four snapshots without an annotated positive objective remain in the full denominator rather than being called negative. "
                "In the stored-medium knockout counterfactual, 63 of 68 scorable MoCo-positive models flip at least one gene call "
                "after the named MoCo biomass coefficients are removed; the reported binomial interval is 0.8367-0.9757. "
                "The total is 511 flipped model-gene calls, not 511 independent genes or wet-lab rescue experiments. "
                "The five zero-flip model IDs are retained in the machine-readable census. The positive-control iJO1366 restores "
                "the moa/mob cluster, including moaD b0784, under the exact counterfactual described in Section 4.3. "
                "See results/bigg_moco_growth_summary.json and per-model results/bigg_moco_growth/*.json.",BODY),
              P('This is a structural falsifiability result: the biomass objective forces a particular knockout prediction. '
                'A flip does not establish that the organism survives the knockout in its real medium. Closely related E. coli '
                'strain models share reaction templates, so neither a simple binomial confidence interval nor the 63/68 fraction '
                'can be read as 68 biologically independent replications. The result supports an audit of biomass-composition '
                'assumptions across reconstruction families, not the assertion that every objective is wrong. A separate '
                'manual second-family verification was subsequently completed on Pseudomonas putida iJN1463 (next paragraph).',BODY),
              P(f"Independent-code second-family check: in the downloaded Pseudomonas putida KT2440 iJN1463 snapshot, three negative MoCo objective coefficients "
                f"({', '.join(second['objective_negative_moco_coefficients'])}) were removed explicitly. The baseline wild-type optimum was {second['baseline_wt_growth']:.6f}/h; "
                f"the patched optimum was {second['patched_wt_growth']:.6f}/h. A fresh complete gene-deletion run found {second['baseline_essential_genes']} baseline-essential genes, "
                f"of which {len(second['flips_from_fresh_manual_counterfactual'])} flipped to growth at least 95% of the original wild type. "
                f"The independently calculated gene IDs are {', '.join(second['flips_from_fresh_manual_counterfactual'])}; each was separately zero-growth under its original model. "
                'The raw model snapshot SHA-256 was checked against the provider-index ledger before use; results/bigg_second_family_verification.json records coefficients, growth and gene IDs. '
                'This meets the narrow second-model-family structural criterion, but Pseudomonas viability in a lab was not tested; related model templates may still limit independence.',BODY),
              P('7.2 Calibration gate: concise audit',H2),
              P('The follow-up gate was written down before scoring in notes/prereg_calibration_decision_gate.md. It asked '
                'whether the stacked gene-essentiality score crossed two tests on the 1,249 aligned genes: G1 AUROC >0.666 '
                'against iJO1366 minimal FBA, and G2 non-significant two-sided McNemar discordance (p >=0.05) with at least '
                'as many model wins as FBA wins. A1 locked a symmetric MCC-based threshold selector on the other two folds for '
                'both candidate and comparator, plus an ordered five-rung ladder. The earlier 27:50 discordant loss came from '
                'eval-inclusive F1-tuned thresholds, so A1 retains it as a harness reproduction, not as a clean baseline. '
                'The gate text stays fixed despite seeing a favorable-direction p-value.',BODY)]
    data=[['rung','AUROC','F1','model-only correct','FBA-only correct','McNemar 2-sided p','literal G2']]
    for r in c['ladder']:
        m=r['mcnemar_vs_comparator'];data.append([r['rung'],f"{r['auroc']:.4f}",f"{r['f1']:.4f}",str(m['b_ensemble_wins']),str(m['c_fba_wins']),f"{m['p_exact_2sided']:.5f}",'PASS' if m['g2_pass'] else 'FAIL'])
    story += tbl(data,'Table 21. Frozen G2 ladder. The significance clause p >=0.05 fails even when the sign favors the ensemble. G1 holds for every rung; no rung passes both clauses.')
    story += [P('R1 has 93 model-only correct versus 67 FBA-only correct calls, with exact p=0.04777. '
                'R2 has 98 versus 58, p=0.00170. Every rung gains more than it loses, but every rung has p<0.05, '
                'so the literal precommitted G2 FAILS. Changing it to a one-sided loss test after seeing results would '
                'misrepresent the preregistration. The observation can motivate a fresh study; it cannot retrospectively '
                'repair this one. The discrimination gain is real as a numerical OOF summary, but its inferential claims '
                'also need the lineage audit in the next section.',BODY),
              P('7.3 Limit on hard-call inference',H2),
              P('The literal G2 gate above failed. A later score-lineage audit found that threshold selection used other-fold OOF scores whose supervised training complements could include the evaluated fold labels; supervised base-layer scores add another nesting concern. Thus the favorable discordant counts are descriptive, not a clean held-out hard-call result. A fully nested refit or untouched cohort is needed. The FBA comparator thresholds yielded the same calls as fixed >0.5 for all 1,249 genes (results/calibration_lineage_audit.json). The locked gate and full fold-level audit remain in the repository; neither was revised after its result.',BODY),
              P('7.4 Judge-informed research direction: where a virtual cell adds information',H2),
              P('The first recorded ChatGPT judge round was asked to critique the calibration paradox and propose a '
                'testable novelty analysis. Its critique identified fold provenance, leakage, comparator-threshold '
                'stability and multiplicity; its scientific suggestion was to ask whether the ensemble advantage '
                'over FBA concentrates in genes with strong transcriptional regulation but weak direct metabolic '
                'constraint. We wrote notes/prereg_discordance_regimes.md as an explicit future mechanism test. '
                'It requires a versioned E. coli transcription-factor-target map, a metabolic-constraint definition '
                'verified against code, matched/negative control partitions and an independent essentiality screen. '
                'STRING association degree is not a substitute for TF regulation. Existing Gerdes OOF outcomes '
                'cannot be recycled as confirmation after they inspired the hypothesis. This new protocol is a '
                'methodological novelty, not an observed biological discovery.',BODY),
              P('7.5 Independent assay as a different question',H2),
              P(f"The published Rousset et al. 2018 genome-wide CRISPRi assay supplies a biologically distinct but non-identical essentiality yardstick (https://doi.org/10.1371/journal.pgen.1007749). A separate pre-registration in notes/prereg_rousset_validation.md fixed median coding-strand depletion <= -5 as the binary outcome, UniProt gene-name mapping, and a ranking comparison against FBA. Of {rv['n_rousset_genes']} source rows, {rv['n_mapped']} map to locus IDs and {rv['n_evaluated']} overlap scored genes, including {rv['n_crispri_essential']} CRISPRi positives. The saved Gerdes-trained v2 score has AUROC {rv['auroc_v2_lr']:.4f} versus FBA {rv['auroc_fba_min']:.4f}; paired gene-bootstrap difference {rv['paired_v2_minus_fba']['mean']:+.4f} [95% CI {rv['paired_v2_minus_fba']['ci95'][0]:+.4f}, {rv['paired_v2_minus_fba']['ci95'][1]:+.4f}]. The study's locked numerical ranking bar was met, as detailed in results/rousset_validation.json and scripts/run_rousset_validation.py.",BODY),
              P('This is genuinely different assay labels, not a new organism, gene universe, or controlled independent training environment. CRISPRi knockdown can exert polar effects in bacterial operons, whereas transposon footprinting and FBA knockouts measure different perturbations. The external label assessment does NOT retroactively validate the defective Gerdes hard-call gate: it evaluates ranking, not a newly selected threshold or matched hard-call specificity. Some CRISPRi measurements may overlap the biology or published annotations used in external features; this needs source provenance review before a strong independence claim. Seven positives in the Gerdes-nonessential subset are too few to support a broad rescue statement despite its attractive AUROC. Report the distinct assay alongside, not in place of, the failed G2 and the MoCo mechanism.',BODY),
              P('7.6 CRISPRi dependence sensitivity',H2),
              P(f"The Rousset comparison uses a distinct assay and a frozen CRISPRi depletion threshold, but gene-name mapping excludes ambiguous or unmapped entries and neighboring operon genes are dependent. A post-result neighborhood-window bootstrap resampled b-number blocks of 5, 10, 20 and 50 IDs (3,000 draws each); the paired AUROC-difference intervals were [{gd['window_bootstrap'][0]['diff_ci95'][0]:+.3f}, {gd['window_bootstrap'][0]['diff_ci95'][1]:+.3f}], [{gd['window_bootstrap'][1]['diff_ci95'][0]:+.3f}, {gd['window_bootstrap'][1]['diff_ci95'][1]:+.3f}], [{gd['window_bootstrap'][2]['diff_ci95'][0]:+.3f}, {gd['window_bootstrap'][2]['diff_ci95'][1]:+.3f}] and [{gd['window_bootstrap'][3]['diff_ci95'][0]:+.3f}, {gd['window_bootstrap'][3]['diff_ci95'][1]:+.3f}]. These remain positive in this proxy grouping, but are not true operon clustering or a new-organism validation (results/rousset_genomic_dependence_audit.json). The separate Gerdes G2 failure is unaffected.",BODY),
              P('7.7 Biomass controls across objective ingredients',H2),
              P(f"A post-result specificity analysis asked whether the same seven-gene objective-dependent rescue could appear after deleting other biomass ingredients. The exploratory protocol in notes/prereg_moco_specificity_null.md was written before controls were computed but was not committed until afterward; it selected every one of {len(mn['controls'])} non-MoCo negative objective coefficients within a factor of two of at least one MoCo coefficient in the saved Pseudomonas iJN1463 model. The source JSON SHA-256 was checked again. Starting from {mn['baseline_essential_genes']} original zero-growth gene deletions, we removed each control coefficient one at a time and retested growth at >=95% original wild type under the same model and medium. The three-term MoCo bundle rescues {mn['positive_bundle']['n_baseline_essential_rescued']} knockout calls; {mn['n_controls_with_rescue_ge_moco_bundle']} of {len(mn['controls'])} single-term controls rescue at least as many. These are adenosylcobalamin (21 calls), biotinyl 5-AMP (8), pyoverdine (14) and thiamine diphosphate (8). Thirty-five controls rescue none. Every ID/count is retained in results/moco_specificity_null_ijn1463.json and the executable script.",BODY),
              P('This is a meaningful exploratory negative result for uniqueness, not a refutation of the MoCo-specific mechanistic gene IDs. Deleting even one alternative objective constituent can cause an equal or larger number of predicted essentiality flips. But comparison of one control coefficient with a three-ingredient MoCo bundle does not match perturbation size; coefficient proximity does not match molecule class, network connectivity or model frequency. Consequently we do not quote an exchangeability-based p-value or rank MoCo as a uniquely causal metabolite from this scout. The result redirects the claimed computational discovery from "MoCo uniquely breaks virtual-cell essentiality" to "biomass composition can make distinct gene calls sensitive to multiple small required terms." Multi-term category- and connectivity-matched controls across model families and condition-matched biological knockout evidence would be needed for a stronger claim. The old Gerdes G2 gate remains failed.',BODY),
              P('7.8 Toward a structure-aware biomass-sensitivity map',H2),
              P(f"We asked whether baseline network features could identify biomass ingredients with fragile essentiality predictions. We built a pre-perturbation, model-hashed feature inventory for all {topo['n_terms']} negative-weight objective compounds in iJN1463. Each row records absolute biomass coefficient, number of non-biomass reactions linked to the compound, count of linked gene-associated reactions, availability of exchange uptake and the number/absolute-flux sum of reactions supplying the compound in the unmodified wild-type optimum. The source hash and 102-row inventory are in results/biomass_topology_manifest.json; none of these features reads knockout outcomes. This is a new systematic method, not a scored predictor.",BODY),
              P('The inventory marks 48 compounds already exposed through the single-term control exercise, three MoCo compounds previously perturbed together only, and 51 additional compounds not singly scored in that exercise. Because target results for 48 compounds were already seen, a regression on all 102 within this one model would be exploratory regardless of when code is committed; leave-one-component-out cross-validation cannot manufacture an independent model family. The protocol in notes/prereg_biomass_topology_sensitivity.md calls for comparable single-term rescoring of all 102, then a separately locked, untouched reconstruction-family test of whether prespecified topology features and a shuffled-feature negative control predict flip counts. Baseline reaction degree and flux are proxies, not full pathway redundancy or biochemical causation. This design does not supersede the failed G2 calibration, the Rousset assay caveats, or the need for wet-lab phenotype checks.',BODY),
              P('7.9 All-term single-coefficient sensitivity',H2),
              P(f"The 102-term feature manifest led to a uniform single-coefficient perturbation audit in iJN1463. The 48 prior controls were preserved as previously seen outcomes; we freshly scored the remaining 54 singles without selecting outcomes or changing the original solver/medium. Across all {ts['n_terms']} terms, {ts['nonzero_flip_terms']} rescue at least one of the original 262 zero-growth gene deletions and {ts['zero_flip_terms']} rescue none. Each of the three MoCo compounds removed *alone* rescues zero, although removing all three together rescues seven; this is a set-interaction property of the objective representation, not evidence that any one of them is an individually powerful lever. The largest single-component effect is lipopolysaccharide LPSpput (29 predicted flips), followed by adenosylcobalamin (21) and pyoverdine (14). No knockout here was biologically tested. Full per-term gene lists and checkpoints are in results/biomass_single_term_sensitivity.json and scripts/score_remaining_biomass_terms.py.",BODY),
              P(f"To ask whether simple baseline features explain these heterogeneous effects, we computed a descriptive Spearman association and 2,000 feature-shuffle controls for five features. Biomass coefficient magnitude correlates with flip count at rho {ts['feature_correlations'][0]['spearman_rho']:+.3f} (permutation p={ts['feature_correlations'][0]['random_feature_permutation_p_two_sided']:.3f}); linked non-biomass reaction count rho {ts['feature_correlations'][1]['spearman_rho']:+.3f} (p={ts['feature_correlations'][1]['random_feature_permutation_p_two_sided']:.3f}); gene-associated reaction count rho {ts['feature_correlations'][2]['spearman_rho']:+.3f} (p={ts['feature_correlations'][2]['random_feature_permutation_p_two_sided']:.3f}). Other baseline-production proxies remain in results/biomass_topology_exploratory.json. None is a registered positive predictive finding. The 48 already seen targets, five inspected features, correlated network summaries, zero-heavy outcome, and single model make these p-values descriptive, not a basis for external generalization. We did not fit a held-out topology predictor. This negative redirects the mechanism question toward multi-term objective interactions and independent model families rather than a simple coefficient or degree rule.",BODY),
              P('7.10 MoCo-subset interaction in iJN1463',H2),
              P("An exploratory seven-subset factorial counterfactual, locked as notes/prereg_moco_subset_interaction.md before pairwise scores, asks which combinations of the three MoCo biomass coefficients are sufficient to undo original zero-growth knockout calls. We used the hashed iJN1463 source, the same full set of 262 baseline-essential genes, and the same rescue threshold of 95% original wild-type growth for all seven nonempty subsets. No singleton rescued a call. Only the bmocogdp_c plus mocogdp_c pair rescued any: six genes (PP_0735, PP_1292, PP_1293, PP_1294, PP_2123 and PP_3457). Adding mobd_c rescued a seventh, PP_3830. The other two pairs rescued zero. The trio result and singletons reproduce previously observed outcomes; the pairwise result is a new mechanistic decomposition within this model, not prospective or external validation.",BODY),
              P("This result narrows the computational interpretation from 'three MoCo terms are individually decisive' to a combination-sensitive dependency: two particular objective demands suffice for six model knockout rescues, while the full three-demand removal is needed for a seventh. It does not prove a physical molecular interaction, because removing biomass coefficients relaxes demands in a mathematical program and the affected genes can share a biosynthetic pathway. No organism was perturbed, the same model supplied every comparison, and the original Gerdes G2 gate remains failed. The exact gene sets, edited wild-type values, source hash, and seven subset outcomes are in results/moco_subset_interaction_ijn1463.json; the reproducible implementation is scripts/score_moco_subset_interaction.py.",BODY),
              P("Model gene-reaction annotations clarify why the seventh call is distinct. PP_0735 (moeB), PP_1292-1294 (moaC/D/E), PP_2123 (moeA) and PP_3457 (mobA) attach to cofactor synthesis in the source reconstruction; PP_3830 (modC) attaches to molybdate ABC transport. The six synthesis-associated genes recover when both guanine-dinucleotide cofactor demands are relaxed, whereas modC only recovers when the remaining molybdate objective demand is also removed. This is a trace through the model's gene-reaction rules, not measured expression, viability, or evidence that a specific cell physiology follows the mathematical combination.",BODY),
              P('7.11 Scope and next validation',H2),



              P('The historical abstract reports the 0.7225 v1 AUROC and 27:50 hard-call loss, which is accurate for '
                'its original eval-inclusive threshold exercise but not the end of the project. The later MoCo census '
                'adds cross-reconstruction structural scope, and the v2 OOF AUROC is approximately 0.7967, yet a '
                'repeated-label score-lineage audit limits the calibration gate. Therefore the defensible headline '
                'today is: a modular model made testable predictions and exposed a biomass-objective artifact; the '
                'later hard-call improvement is suggestive, not a clean held-out win. An independent phenotypic '
                'screen and condition-matched carbon-source evaluation remain needed for the strongest claim.',BODY)]
    return story
