"""Main-body 2026 calibration and structural-discovery updates, preserving the locked failure."""
import json,os
from build_paper import P,H1,H2,BODY,EQ,tbl,fig,ROOT,PageBreak

def story_calibration(story,R):
    bg=R('bigg_model_survey.json'); census=R('bigg_moco_growth_summary.json');c=R('calibration_gate.json');a=R('calibration_lineage_audit.json'); second=R('bigg_second_family_verification.json'); fam=R('postresult_moco_family_dependence.json'); rv=R('rousset_validation.json'); gd=R('rousset_genomic_dependence_audit.json'); mn=R('moco_specificity_null_ijn1463.json'); topo=R('biomass_topology_manifest.json'); ts=R('biomass_topology_exploratory.json'); bt=R('biomass_transfer_iyo844.json'); yeast=R('biomass_transfer_imm904.json'); db=R('biomass_baseline_dominance_audit.json'); sb=R('bsub_rescue_subtiwiki_overlap.json'); pair=R('postresult_equal_coefficient_pair_null.json'); pinter=R('postresult_pair_interactions.json'); fresh=R('postresult_pair_interactions_fresh_check.json'); op=R('rousset_source_operon_sensitivity.json')
    assert census['scorable']==68 and census['models_with_at_least_one_flip']==63
    assert c['verdict']['first_passing_rung'] is None and len(c['ladder'])==5
    story += [PageBreak(),P('7. Later locked studies and audit of the calibration claim',H1),
              P('7.1 BiGG census: distinguishing model structure from biology',H2),
              P(f"The BiGG v2 listing supplied {bg['listed']} unique model accessions, each downloaded and hashed. "
                f"Of these, {len(bg['moco_biomass_models'])} have a positive-weight biomass objective consuming a MoCo-named "
                "compound; four snapshots without an annotated positive objective remain in the full denominator rather than being called negative. "
                "In the stored-medium knockout counterfactual, 63 of 68 scorable MoCo-positive models flip at least one gene call "
                "after the named MoCo biomass coefficients are removed; the reported binomial interval is 0.8367-0.9757. "
                "The total is 511 flipped model-gene calls, not 511 independent genes or wet-lab rescue experiments. "
                "The five zero-flip model IDs are retained in the machine-readable census. The positive-control iJO1366 restores "
                "the moa/mob cluster, including moaD b0784, under the exact counterfactual described in Section 4.3. "
                "See results/bigg_moco_growth_summary.json and per-model results/bigg_moco_growth/*.json.",BODY),
              P('This is a structural falsifiability result: the biomass objective forces a particular knockout prediction. '
                'A flip does not establish that the organism survives the knockout in its real medium. Closely related E. coli '
                'strain models share reaction templates, so neither a simple binomial confidence interval nor the 63/68 fraction '
                'can be read as 68 biologically independent replications. The result supports an audit of biomass-composition '
                'assumptions across reconstruction families, not the assertion that every objective is wrong. A separate '
                'manual second-family verification was subsequently completed on Pseudomonas putida iJN1463 (next paragraph).',BODY),
              P(f"Independent-code second-family check: in the downloaded Pseudomonas putida KT2440 iJN1463 snapshot, three negative MoCo objective coefficients "
                f"({', '.join(second['objective_negative_moco_coefficients'])}) were removed explicitly. The baseline wild-type optimum was {second['baseline_wt_growth']:.6f}/h; "
                f"the patched optimum was {second['patched_wt_growth']:.6f}/h. A fresh complete gene-deletion run found {second['baseline_essential_genes']} baseline-essential genes, "
                f"of which {len(second['flips_from_fresh_manual_counterfactual'])} flipped to growth at least 95% of the original wild type. "
                f"The independently calculated gene IDs are {', '.join(second['flips_from_fresh_manual_counterfactual'])}; each was separately zero-growth under its original model. "
                'The raw model snapshot SHA-256 was checked against the provider-index ledger before use; results/bigg_second_family_verification.json records coefficients, growth and gene IDs. '
                'This meets the narrow second-model-family structural criterion, but Pseudomonas viability in a lab was not tested; related model templates may still limit independence.',BODY),
              P(f"A post-result family-dependence audit of the same saved census (notes/postresult_moco_family_sensitivity.md, scripts/audit_postresult_moco_family_dependence.py, results/postresult_moco_family_dependence.json) makes the concentration concrete. Joining every saved per-model outcome to the hashed survey: among the {fam['escherichia_shigella']['n_model_accessions']} accessions whose stated organism is Escherichia or Shigella, {fam['escherichia_shigella']['n_with_flip']} flip at least one call. Outside those closely related genera the census holds only {fam['other_genera']['n_model_accessions']} accessions (Clostridium iHN637, Pseudomonas iJN1463, Synechocystis iJN678, Salmonella STM_v1_0), of which {fam['other_genera']['n_with_flip']} flip: Pseudomonas and Synechocystis, while Clostridium and Salmonella do not. Identical eight-call flip sets recur across E. coli strain models with strain-specific gene IDs. The 63/68 headline therefore does not supply 63 independent cross-family confirmations; the cross-family evidence rests on four non-enteric reconstructions and shares model-curation templates. This is an outcome-aware descriptive re-tabulation, not new phenotypic evidence, and it does not change the failed G2 gate.",BODY),
              P('7.2 Calibration gate: concise audit',H2),
              P('The follow-up gate was written down before scoring in notes/prereg_calibration_decision_gate.md. It asked '
                'whether the stacked gene-essentiality score crossed two tests on the 1,249 aligned genes: G1 AUROC >0.666 '
                'against iJO1366 minimal FBA, and G2 non-significant two-sided McNemar discordance (p >=0.05) with at least '
                'as many model wins as FBA wins. A1 locked a symmetric MCC-based threshold selector on the other two folds for '
                'both candidate and comparator, plus an ordered five-rung ladder. The earlier 27:50 discordant loss came from '
                'eval-inclusive F1-tuned thresholds, so A1 retains it as a harness reproduction, not as a clean baseline. '
                'The gate text stays fixed despite seeing a favorable-direction p-value.',BODY)]
    data=[['rung','AUROC','F1','model-only correct','FBA-only correct','McNemar 2-sided p','literal G2']]
    for r in c['ladder']:
        m=r['mcnemar_vs_comparator'];data.append([r['rung'],f"{r['auroc']:.4f}",f"{r['f1']:.4f}",str(m['b_ensemble_wins']),str(m['c_fba_wins']),f"{m['p_exact_2sided']:.5f}",'PASS' if m['g2_pass'] else 'FAIL'])
    story += tbl(data,'Table 21. Frozen G2 ladder. The significance clause p >=0.05 fails even when the sign favors the ensemble. G1 holds for every rung; no rung passes both clauses.')
    story += [P('R1 has 93 model-only correct versus 67 FBA-only correct calls, with exact p=0.04777. '
                'R2 has 98 versus 58, p=0.00170. Every rung gains more than it loses, but every rung has p<0.05, '
                'so the literal precommitted G2 FAILS. Changing it to a one-sided loss test after seeing results would '
                'misrepresent the preregistration. The observation can motivate a fresh study; it cannot retrospectively '
                'repair this one. The discrimination gain is real as a numerical OOF summary, but its inferential claims '
                'also need the lineage audit in the next section.',BODY),
              P('7.3 Limit on hard-call inference',H2),
              P('The literal G2 gate above failed. A later score-lineage audit found that threshold selection used other-fold OOF scores whose supervised training complements could include the evaluated fold labels; supervised base-layer scores add another nesting concern. Thus the favorable discordant counts are descriptive, not a clean held-out hard-call result. A fully nested refit or untouched cohort is needed. The FBA comparator thresholds yielded the same calls as fixed >0.5 for all 1,249 genes (results/calibration_lineage_audit.json). The locked gate and full fold-level audit remain in the repository; neither was revised after its result.',BODY),
              P('7.3a New exploratory nested-threshold follow-up (not a gate repair)',H2),
              P('After the lineage flaw was known, we locked a separate follow-up with an outer three-fold split, '
                'inner-fold out-of-fold score generation for threshold selection, and fresh outer-training refits '
                '(notes/prereg_nested_threshold_followup.md). The feature set excludes the previously reused '
                'CNN/GNN/k-mer supervised OOF base scores and removes selected external annotation channels; '
                'it is a restricted replacement model, not a nested rerun of the original stack. Each outer '
                'fold chooses its threshold only from inner training scores and labels. The comparator is the '
                'pre-specified label-free FBA minimal >0.5 call.',BODY),
              P('On the same 1,249 Gerdes-overlap genes, this exploratory model obtains outer-fold OOF '
                'AUROC 0.7714, AUPRC 0.4590, F1 0.4978 and MCC 0.3891; FBA minimal is AUROC 0.6658, '
                'F1 0.4099 and MCC 0.2970 on those rows. There are 85 model-only-correct and 70 '
                'FBA-only-correct calls (exact two-sided McNemar p=0.2607). Non-significance is not '
                'equivalence, and these scores cannot be substituted into the old G2 gate, which remains FAIL '
                'on all five rungs. The Gerdes cohort and external annotations are reused after prior '
                'results were inspected; this is an exploratory leakage-reduced evaluation, not a new '
                'untouched test or proof that all feature provenance is label-free. See '
                'results/nested_threshold_followup.json and its gene-level OOF CSV.',BODY),
              P('7.4 Judge-informed research direction: where a virtual cell adds information',H2),
              P('The first recorded ChatGPT judge round was asked to critique the calibration paradox and propose a '
                'testable novelty analysis. Its critique identified fold provenance, leakage, comparator-threshold '
                'stability and multiplicity; its scientific suggestion was to ask whether the ensemble advantage '
                'over FBA concentrates in genes with strong transcriptional regulation but weak direct metabolic '
                'constraint. We wrote notes/prereg_discordance_regimes.md as an explicit future mechanism test. '
                'It requires a versioned E. coli transcription-factor-target map, a metabolic-constraint definition '
                'verified against code, matched/negative control partitions and an independent essentiality screen. '
                'STRING association degree is not a substitute for TF regulation. Existing Gerdes OOF outcomes '
                'cannot be recycled as confirmation after they inspired the hypothesis. This new protocol is a '
                'methodological novelty, not an observed biological discovery.',BODY),
              P('7.5 Independent assay as a different question',H2),
              P(f"The published Rousset et al. 2018 genome-wide CRISPRi assay supplies a biologically distinct but non-identical essentiality yardstick (https://doi.org/10.1371/journal.pgen.1007749). A separate pre-registration in notes/prereg_rousset_validation.md fixed median coding-strand depletion <= -5 as the binary outcome, UniProt gene-name mapping, and a ranking comparison against FBA. Of {rv['n_rousset_genes']} source rows, {rv['n_mapped']} map to locus IDs and {rv['n_evaluated']} overlap scored genes, including {rv['n_crispri_essential']} CRISPRi positives. The saved Gerdes-trained v2 score has AUROC {rv['auroc_v2_lr']:.4f} versus FBA {rv['auroc_fba_min']:.4f}; paired gene-bootstrap difference {rv['paired_v2_minus_fba']['mean']:+.4f} [95% CI {rv['paired_v2_minus_fba']['ci95'][0]:+.4f}, {rv['paired_v2_minus_fba']['ci95'][1]:+.4f}]. The study's locked numerical ranking bar was met, as detailed in results/rousset_validation.json and scripts/run_rousset_validation.py.",BODY),
              P('This is genuinely different assay labels, not a new organism, gene universe, or controlled independent training environment. CRISPRi knockdown can exert polar effects in bacterial operons, whereas transposon footprinting and FBA knockouts measure different perturbations. The external label assessment does NOT retroactively validate the defective Gerdes hard-call gate: it evaluates ranking, not a newly selected threshold or matched hard-call specificity. Some CRISPRi measurements may overlap the biology or published annotations used in external features; this needs source provenance review before a strong independence claim. Seven positives in the Gerdes-nonessential subset are too few to support a broad rescue statement despite its attractive AUROC. Report the distinct assay alongside, not in place of, the failed G2 and the MoCo mechanism.',BODY),
              P('7.6 CRISPRi dependence sensitivity',H2),
              P(f"The Rousset comparison uses a distinct assay and a frozen CRISPRi depletion threshold, but gene-name mapping excludes ambiguous or unmapped entries and neighboring operon genes are dependent. A post-result neighborhood-window bootstrap resampled b-number blocks of 5, 10, 20 and 50 IDs (3,000 draws each); the paired AUROC-difference intervals were [{gd['window_bootstrap'][0]['diff_ci95'][0]:+.3f}, {gd['window_bootstrap'][0]['diff_ci95'][1]:+.3f}], [{gd['window_bootstrap'][1]['diff_ci95'][0]:+.3f}, {gd['window_bootstrap'][1]['diff_ci95'][1]:+.3f}], [{gd['window_bootstrap'][2]['diff_ci95'][0]:+.3f}, {gd['window_bootstrap'][2]['diff_ci95'][1]:+.3f}] and [{gd['window_bootstrap'][3]['diff_ci95'][0]:+.3f}, {gd['window_bootstrap'][3]['diff_ci95'][1]:+.3f}]. These remain positive in this proxy grouping, but are not true operon clustering or a new-organism validation (results/rousset_genomic_dependence_audit.json). The separate Gerdes G2 failure is unaffected.",BODY),
              P('7.6a Source-operon grouped sensitivity (exploratory)',H2),
              P(f"The Rousset S12 source table includes operon labels, allowing a stronger dependence check "
                f"than arbitrary b-number windows. After the original Rousset score was known, we locked an "
                f"exploratory protocol and grouped the {op['n_genes']} mapped genes by source operon string: "
                f"{op['n_source_operon_groups']} groups, of which {op['n_multigene_groups']} contain multiple "
                f"genes and {op['n_groups_with_positive']} contain a CRISPRi positive. The gene-level AUROC "
                f"difference (v2 minus FBA) is {op['gene_level_difference']:+.3f}. Resampling source-operon "
                f"groups in {op['group_bootstrap']['n_draws_valid']} fixed-seed draws gives a descriptive "
                f"95% interval [{op['group_bootstrap']['diff_ci95'][0]:+.3f}, "
                f"{op['group_bootstrap']['diff_ci95'][1]:+.3f}]; choosing one gene per group in "
                f"{op['one_gene_per_operon']['n_draws_valid']} draws gives "
                f"[{op['one_gene_per_operon']['diff_ci95'][0]:+.3f}, "
                f"{op['one_gene_per_operon']['diff_ci95'][1]:+.3f}]. Both remain positive as dependence "
                f"diagnostics. Shared operon strings do not prove a polar effect in this assay, and these "
                f"same-accession post-result resamples neither establish an independent cohort nor repair G2. "
                f"Source mappings and all gene-level scores are retained in "
                f"results/rousset_source_operon_mapped.csv; the protocol and numeric result are in "
                f"notes/prereg_rousset_operon_sensitivity.md and results/rousset_source_operon_sensitivity.json.",BODY),
              P('7.7 Biomass controls across objective ingredients',H2),
              P(f"A post-result specificity analysis asked whether the same seven-gene objective-dependent rescue could appear after deleting other biomass ingredients. The exploratory protocol in notes/prereg_moco_specificity_null.md was written before controls were computed but was not committed until afterward; it selected every one of {len(mn['controls'])} non-MoCo negative objective coefficients within a factor of two of at least one MoCo coefficient in the saved Pseudomonas iJN1463 model. The source JSON SHA-256 was checked again. Starting from {mn['baseline_essential_genes']} original zero-growth gene deletions, we removed each control coefficient one at a time and retested growth at >=95% original wild type under the same model and medium. The three-term MoCo bundle rescues {mn['positive_bundle']['n_baseline_essential_rescued']} knockout calls; {mn['n_controls_with_rescue_ge_moco_bundle']} of {len(mn['controls'])} single-term controls rescue at least as many. These are adenosylcobalamin (21 calls), biotinyl 5-AMP (8), pyoverdine (14) and thiamine diphosphate (8). Thirty-five controls rescue none. Every ID/count is retained in results/moco_specificity_null_ijn1463.json and the executable script.",BODY),
              P('This is a meaningful exploratory negative result for uniqueness, not a refutation of the MoCo-specific mechanistic gene IDs. Deleting even one alternative objective constituent can cause an equal or larger number of predicted essentiality flips. But comparison of one control coefficient with a three-ingredient MoCo bundle does not match perturbation size; coefficient proximity does not match molecule class, network connectivity or model frequency. Consequently we do not quote an exchangeability-based p-value or rank MoCo as a uniquely causal metabolite from this scout. The result redirects the claimed computational discovery from "MoCo uniquely breaks virtual-cell essentiality" to "biomass composition can make distinct gene calls sensitive to multiple small required terms." Multi-term category- and connectivity-matched controls across model families and condition-matched biological knockout evidence would be needed for a stronger claim. The old Gerdes G2 gate remains failed.',BODY),
              P('7.8 Toward a structure-aware biomass-sensitivity map',H2),
              P(f"We asked whether baseline network features could identify biomass ingredients with fragile essentiality predictions. We built a pre-perturbation, model-hashed feature inventory for all {topo['n_terms']} negative-weight objective compounds in iJN1463. Each row records absolute biomass coefficient, number of non-biomass reactions linked to the compound, count of linked gene-associated reactions, availability of exchange uptake and the number/absolute-flux sum of reactions supplying the compound in the unmodified wild-type optimum. The source hash and 102-row inventory are in results/biomass_topology_manifest.json; none of these features reads knockout outcomes. This is a new systematic method, not a scored predictor.",BODY),
              P('The inventory marks 48 compounds already exposed through the single-term control exercise, three MoCo compounds previously perturbed together only, and 51 additional compounds not singly scored in that exercise. Because target results for 48 compounds were already seen, a regression on all 102 within this one model would be exploratory regardless of when code is committed; leave-one-component-out cross-validation cannot manufacture an independent model family. The protocol in notes/prereg_biomass_topology_sensitivity.md calls for comparable single-term rescoring of all 102, then a separately locked, untouched reconstruction-family test of whether prespecified topology features and a shuffled-feature negative control predict flip counts. Baseline reaction degree and flux are proxies, not full pathway redundancy or biochemical causation. This design does not supersede the failed G2 calibration, the Rousset assay caveats, or the need for wet-lab phenotype checks.',BODY),
              P('7.9 All-term single-coefficient sensitivity',H2),
              P(f"The 102-term feature manifest led to a uniform single-coefficient perturbation audit in iJN1463. The 48 prior controls were preserved as previously seen outcomes; we freshly scored the remaining 54 singles without selecting outcomes or changing the original solver/medium. Across all {ts['n_terms']} terms, {ts['nonzero_flip_terms']} rescue at least one of the original 262 zero-growth gene deletions and {ts['zero_flip_terms']} rescue none. Each of the three MoCo compounds removed *alone* rescues zero, although removing all three together rescues seven; this is a set-interaction property of the objective representation, not evidence that any one of them is an individually powerful lever. The largest single-component effect is lipopolysaccharide LPSpput (29 predicted flips), followed by adenosylcobalamin (21) and pyoverdine (14). No knockout here was biologically tested. Full per-term gene lists and checkpoints are in results/biomass_single_term_sensitivity.json and scripts/score_remaining_biomass_terms.py.",BODY),
              P(f"To ask whether simple baseline features explain these heterogeneous effects, we computed a descriptive Spearman association and 2,000 feature-shuffle controls for five features. Biomass coefficient magnitude correlates with flip count at rho {ts['feature_correlations'][0]['spearman_rho']:+.3f} (permutation p={ts['feature_correlations'][0]['random_feature_permutation_p_two_sided']:.3f}); linked non-biomass reaction count rho {ts['feature_correlations'][1]['spearman_rho']:+.3f} (p={ts['feature_correlations'][1]['random_feature_permutation_p_two_sided']:.3f}); gene-associated reaction count rho {ts['feature_correlations'][2]['spearman_rho']:+.3f} (p={ts['feature_correlations'][2]['random_feature_permutation_p_two_sided']:.3f}). Other baseline-production proxies remain in results/biomass_topology_exploratory.json. None is a registered positive predictive finding. The 48 already seen targets, five inspected features, correlated network summaries, zero-heavy outcome, and single model make these p-values descriptive, not a basis for external generalization. We did not fit a held-out topology predictor. This negative redirects the mechanism question toward multi-term objective interactions and independent model families rather than a simple coefficient or degree rule.",BODY),
              P('7.10 MoCo-subset interaction in iJN1463',H2),
              P("An exploratory seven-subset factorial counterfactual, locked as notes/prereg_moco_subset_interaction.md before pairwise scores, asks which combinations of the three MoCo biomass coefficients are sufficient to undo original zero-growth knockout calls. We used the hashed iJN1463 source, the same full set of 262 baseline-essential genes, and the same rescue threshold of 95% original wild-type growth for all seven nonempty subsets. No singleton rescued a call. Only the bmocogdp_c plus mocogdp_c pair rescued any: six genes (PP_0735, PP_1292, PP_1293, PP_1294, PP_2123 and PP_3457). Adding mobd_c rescued a seventh, PP_3830. The other two pairs rescued zero. The trio result and singletons reproduce previously observed outcomes; the pairwise result is a new mechanistic decomposition within this model, not prospective or external validation.",BODY),
              P("This result narrows the computational interpretation from 'three MoCo terms are individually decisive' to a combination-sensitive dependency: two particular objective demands suffice for six model knockout rescues, while the full three-demand removal is needed for a seventh. It does not prove a physical molecular interaction, because removing biomass coefficients relaxes demands in a mathematical program and the affected genes can share a biosynthetic pathway. No organism was perturbed, the same model supplied every comparison, and the original Gerdes G2 gate remains failed. The exact gene sets, edited wild-type values, source hash, and seven subset outcomes are in results/moco_subset_interaction_ijn1463.json; the reproducible implementation is scripts/score_moco_subset_interaction.py.",BODY),
              P("Model gene-reaction annotations clarify why the seventh call is distinct. PP_0735 (moeB), PP_1292-1294 (moaC/D/E), PP_2123 (moeA) and PP_3457 (mobA) attach to cofactor synthesis in the source reconstruction; PP_3830 (modC) attaches to molybdate ABC transport. The six synthesis-associated genes recover when both guanine-dinucleotide cofactor demands are relaxed, whereas modC only recovers when the remaining molybdate objective demand is also removed. This is a trace through the model's gene-reaction rules, not measured expression, viability, or evidence that a specific cell physiology follows the mathematical combination.",BODY),
              P('7.11 Transfer of a frozen biomass-fragility score to a distinct reconstruction',H2),
              P(f"To check whether the topology features carry any information beyond the Pseudomonas model, we froze a five-feature logistic model trained on its 102 biomass constituents (23 positive single-coefficient rescues), then scored all {bt['n_terms']} negative biomass coefficients in Bacillus subtilis iYO844 before observing their knockout outcomes. The target reconstruction was chosen by organism family and absence of MoCo-named biomass terms, with source SHA-256 checked against the existing BiGG ledger. Every predicted probability was committed before deleting a target coefficient (notes/prereg_biomass_transfer_iyo844.md and results/biomass_transfer_iyo844_frozen_predictions.json). In the target model, {bt['n_positive']} of {bt['n_terms']} coefficients rescue at least one original zero-growth knockout after deletion. Frozen-score AUROC is {bt['auroc']:.4f}; average precision {bt['average_precision']:.4f} versus positive prevalence {bt['target_prevalence']:.4f}. A 1,000-shuffle label-relative-to-feature control gives an AUROC one-sided tail fraction {bt['null_feature_shuffle_auc_p_one_sided']:.4f}, but AP tail fraction {bt['null_feature_shuffle_ap_p_one_sided']:.4f}. Brier loss is {bt['brier']:.4f}, worse than {bt['brier_constant_train_prevalence']:.4f} for a constant training-prevalence forecast. The numerical ranking signal is modest and its probability calibration is poor; it does not meet a general predictor claim.",BODY),
              P('This is an out-of-model computational test, not an independent phenotypic screen: both reconstructions come from the BiGG modeling ecosystem and differ in medium, species, biomass demands and gene-rule detail. The outcome is a simulation of relaxing the objective rather than a measured essentiality rescue. The score ranks ATP and menaquinol-7 among target-sensitive terms but also rates water and potassium highly despite zero rescue, making a mechanistic or deployment claim premature. All 60 prediction/outcome rows, rescued-gene sets, edited growth values and the frozen training script are retained in results/biomass_transfer_iyo844.json and scripts/run_biomass_transfer_iyo844.py. An additional reconstruction-family check is in Section 7.12; condition-matched wet-lab knockout outcomes remain necessary. G2 remains failed.',BODY),
              P('7.12 Second out-of-model transfer: yeast iMM904',H2),
              P(f"After seeing the Bacillus result, we froze a second reconstruction-family transfer to the already downloaded BiGG Saccharomyces cerevisiae iMM904 model. Its source URL and SHA-256 were checked against the prior census; the same untouched Pseudomonas-trained five-feature score was run on all {yeast['n_terms']} negative biomass objective ingredients, and its predicted probabilities were committed before any target knockout rescoring (notes/prereg_biomass_transfer_yeast_imm904.md; results/biomass_transfer_imm904_frozen_predictions.json). {yeast['n_positive']} of {yeast['n_terms']} constituents rescue at least one originally zero-growth in-model knockout on single-coefficient removal. The frozen score gives AUROC {yeast['auroc']:.4f}, average precision {yeast['average_precision']:.4f} versus target prevalence {yeast['target_prevalence']:.4f}, and Brier {yeast['brier']:.4f} versus {yeast['brier_constant_train_prevalence']:.4f} for constant Pseudomonas-training prevalence. One-thousand-shuffle label-relative-to-feature tail fractions are {yeast['null_feature_shuffle_auc_p_one_sided']:.4f} (AUROC) and {yeast['null_feature_shuffle_ap_p_one_sided']:.4f} (AP), neither a registered success. ATP is a correctly ranked sensitive component (10 rescued calls), but water is again highly ranked and rescues none. The two target reconstructions give inconsistent calibration and only modest discrimination; we do not infer a transferable general predictor from them.",BODY),
              P('The yeast result is an honest negative/ambiguous computational generalization test, not biological validation. All three models come from BiGG and share curation conventions; biomass reactions, media and organism physiology differ. The per-term target effects are predictions under relaxed model objectives, not measured survival. A model-source-distinct, condition-matched experimental knockout screen is still needed to test whether objective-fragility forecasts improve real essentiality calls. The exact 44 yeast rows, original positive-call gene lists and reproducible script are in results/biomass_transfer_imm904.json and scripts/run_biomass_transfer_imm904.py. The failed Gerdes G2 hard-call gate is not changed.',BODY),
              P('7.13 Simple baselines and ubiquitous-component influence',H2),
              P(f"A post-result diagnostic asks whether the frozen five-feature score adds anything over two one-variable rules: rank by larger absolute biomass coefficient, or by fewer gene-associated reactions linked to the required metabolite. In Bacillus, the five-feature score AUROC/AP are {db['targets']['iyo844']['full']['frozen_five_feature']['auroc']:.3f}/{db['targets']['iyo844']['full']['frozen_five_feature']['average_precision']:.3f}; coefficient-only {db['targets']['iyo844']['full']['coefficient_magnitude']['auroc']:.3f}/{db['targets']['iyo844']['full']['coefficient_magnitude']['average_precision']:.3f}; inverse-degree-only {db['targets']['iyo844']['full']['inverse_gene_associated_degree']['auroc']:.3f}/{db['targets']['iyo844']['full']['inverse_gene_associated_degree']['average_precision']:.3f}. In yeast those pairs are {db['targets']['imm904']['full']['frozen_five_feature']['auroc']:.3f}/{db['targets']['imm904']['full']['frozen_five_feature']['average_precision']:.3f}, {db['targets']['imm904']['full']['coefficient_magnitude']['auroc']:.3f}/{db['targets']['imm904']['full']['coefficient_magnitude']['average_precision']:.3f}, and {db['targets']['imm904']['full']['inverse_gene_associated_degree']['auroc']:.3f}/{db['targets']['imm904']['full']['inverse_gene_associated_degree']['average_precision']:.3f}. Yeast inverse-degree AUROC slightly exceeds the five-feature score; there is no consistent multi-feature dominance, and these simple rules were evaluated only after the target outcomes were seen.",BODY),
              P(f"Two metabolites illustrate how a globally shared biomass ingredient can dominate model ranking: ATP scores near the top and rescues {db['targets']['iyo844']['atp_and_water'][0]['rescued_count'] if db['targets']['iyo844']['atp_and_water'][0]['metabolite_id']=='atp_c' else db['targets']['iyo844']['atp_and_water'][1]['rescued_count']} Bacillus original knockout calls, whereas water is also high-ranked but rescues none. Descriptively removing exactly ATP and water without refitting leaves Bacillus AUROC {db['targets']['iyo844']['without_atp_and_water']['auroc']:.3f} and AP {db['targets']['iyo844']['without_atp_and_water']['average_precision']:.3f} on {db['targets']['iyo844']['without_atp_and_water']['n']} terms; yeast AUROC {db['targets']['imm904']['without_atp_and_water']['auroc']:.3f} and AP {db['targets']['imm904']['without_atp_and_water']['average_precision']:.3f} on {db['targets']['imm904']['without_atp_and_water']['n']} terms. Rankings do not collapse but remain modest and calibration is unproven. This outcome-known influence analysis cannot be repackaged as a cleaner prospective test. Full term scores and control details are in results/biomass_baseline_dominance_audit.json, with fixed protocol and executable script.",BODY),
              P('7.14 Biological-label contradiction check in Bacillus',H2),
              P(f"The BiGG coefficient-removal outcomes are computational, so we tested whether their rescued gene names overlap with a previously obtained biological-label category rather than calling every flip a biological rescue. The local SubtiWiki essential-gene category yielded {sb['n_subtiwiki_names']} parsed names (source page and hash in results/bsub_rescue_subtiwiki_overlap.json). The page states 251 protein and two RNA essential genes, so the parsed 260 names are not a clean single-study label set. The iYO844 reconstruction itself used essentiality evidence in model development; independence from these labels cannot be claimed. Of {sb['baseline_model_essential']['n_source_gene_ids']} originally zero-growth iYO844 model gene knockouts, {sb['baseline_model_essential']['n_unique_name_mapped']} map to unique gene names and {sb['baseline_model_essential']['n_in_subtiwiki_essential_list']} names appear in that list. Across all 17 biomass-term counterfactuals that rescue any model gene, the union has {sb['rescued_union']['n_source_gene_ids']} distinct gene IDs, {sb['rescued_union']['n_unique_name_mapped']} uniquely named and {sb['rescued_union']['n_in_subtiwiki_essential_list']} listed on SubtiWiki. This is a descriptive contradiction warning for any claim that a relaxed objective proves viability, not a condition-matched falsification of the model: deletion-library medium and strain may differ from the in-silico stored medium.",BODY),
              P("Two pathways expose the issue concretely. Removing the menaquinol-7 objective coefficient rescues 16 in-model knockout calls, yet 11 of those gene names remain on the SubtiWiki list, including menA/B/C/D/E and isoprenoid-precursor genes. Removing the peptidoglycan objective term rescues 9, of which 8 listed names include murB/C/D/E/F/G, mraY and ddl. A name absent from the list is not verified viable under matched conditions; mapping is not enough to infer phenotype. Full gene/term name matches, one unnamed original gene, source URL and both file hashes are preserved in results/bsub_rescue_subtiwiki_overlap.json and scripts/audit_bsub_rescues_subtiwiki.py. This post-result cross-list sanity check narrows the computational conclusion to objective-dependence, not confirmed biological rescue. It does not alter G2.",BODY),
              P('7.15 Retrospective equal-coefficient pair controls',H2),
              P(f"The MoCo subset analysis found six knockout rescues when bmocogdp_c and mocogdp_c were removed together. Because the earlier negative control compared a three-term MoCo bundle with other single-term deletions, we retrospectively enumerated all {pair['n_pairs']} unordered pairs among {len(pair['eligible_non_moco_terms'])} non-MoCo objective ingredients with the same negative biomass coefficient (-0.000223) as each MoCo pair member. The source snapshot and medium are unchanged and its SHA-256 is checked before scoring. All original {pair['n_original_zero_growth_genes']} zero-growth gene deletions were tested after each two-coefficient deletion, with rescue fixed at at least 95% of original, unedited wild-type growth. A fresh MoCo-pair rerun reproduced the six gene IDs and edited wild-type growth from the previous seven-subset audit. Exact candidate IDs, pair outcomes and rescued gene IDs are stored in results/postresult_equal_coefficient_pair_null.json; notes/postresult_equal_coefficient_pair_null.md fixes the protocol, which was locked before these pair outcomes but after the MoCo outcome was already known.",BODY),
              P(f"Of {pair['n_pairs']} non-MoCo pairs, {pair['summary']['n_pairs_ge_mo_six']} rescue at least six original knockout calls and {pair['summary']['n_pairs_gt_mo_six']} exceed six; {pair['summary']['zero_rescue_pairs']} rescue none. The largest pair, adenosylcobalamin plus pyoverdine, rescues {pair['summary']['max_non_moco_rescues']}. Thus the two-term MoCo perturbation is not exceptional by aggregate rescue count when coefficient size and number of deleted terms are matched. None of the six original MoCo-pair rescued gene IDs is rescued by any of these {pair['n_pairs']} non-MoCo pairs; the exact gene-set pattern is distinctive within this finite enumeration, although all six may share one cofactor pathway. No LP solver failures were observed.",BODY),
              P('This comparison is an outcome-aware sensitivity analysis, not an exchangeable randomization experiment: equal coefficient size and pair cardinality do not match biochemical class, network topology, biomass-coupling constraints or uptake. Its descriptive rank is not a p-value. The result supports a narrower model-level claim: several biomass demands cause equal or larger total hard-call changes, while the MoCo-pair perturbation selects this particular six-gene pattern in the source reconstruction. It neither shows that any cell survives a knockout nor repairs the failed Gerdes G2 gate. Category-matched multi-model controls and condition-matched phenotype evidence remain necessary.',BODY),
              P('7.16 Pair interactions reveal an objective-stoichiometry trap',H2),
              P(f"A retrospective gene-set reconciliation checked whether each of the {pinter['n_pairs']} scored non-MoCo pairs rescued exactly the union of the knockout calls rescued by its two component deletions. {pinter['n_exact_single_union']} pairs matched that simple union; {pinter['n_pair_only']} had new pair-only genes and {pinter['n_lost_single_union']} lost calls present in a single-term outcome. This was computed only after all pair and single outcomes were visible, and does not create another independent experiment. Among the exceptions, deleting both heme O and protoheme objective coefficients rescued three genes (PP_0189, PP_0744, PP_5074) where either singleton rescued none; deleting both adenosylcobalamin and FAD rescued PP_0602 in addition to the adenosylcobalamin-only set of 21. The original two-term MoCo pair, whose singletons rescue zero, has six pair-only calls. The exact sets, including 250 ordinary pairs, are retained in results/postresult_pair_interactions.json.",BODY),
              P("The opposite exception matters even more for interpretation: deleting the [2Fe-2S] cluster coefficient alongside biotinyl 5-AMP eliminates the eight rescue calls seen for biotinyl 5-AMP alone. A fresh model reload for each unmodified, singleton and pair variant reproduced every candidate growth status as optimal and all recorded gene sets. The double-edited wild-type optimum fell from 0.586118 to 0.390006, whereas the biotinyl 5-AMP-only optimum was 0.586229. Thus editing two terms is NOT guaranteed to behave as merely relaxing two independent biomass requirements; the modified stoichiometric objective can change the LP feasible-growth balance in either direction. These are in-model interaction patterns, not measured molecular epistasis. The fresh statuses, gene growth values and source hash are in results/postresult_pair_interactions_fresh_check.json. No new hard-call gate or biological viability claim follows.",BODY),
              P('7.16a Which pair interactions break the single-term union rule?',H2),
              P('A useful operational null for biomass editing is set union: if removing each ingredient '
                'separately rescues a set of gene deletions, would removing both rescue exactly the union? '
                'This is not a theorem of linear programming because changing a biomass coefficient '
                'changes the objective stoichiometry as well as the attainable optimum. The 253 scored '
                'non-MoCo two-term edits give 250 exact gene-set unions and three exceptions. The '
                'exceptions are not random samples and were identified after the scores were seen; '
                'they are finite computational counterexamples to a tempting shortcut, not '
                'population estimates of how often biochemical interactions occur.',BODY),
              ]
    exceptions=[x for x in pinter['rows'] if x['pair_only_genes'] or x['single_union_only_genes']]
    assert len(exceptions)==3 and pinter['n_exact_single_union']==250
    story += tbl([['removed pair','single A','single B','union','pair','new-only','lost-union']]
                 + [[" + ".join(x['pair']),str(x['single_a_count']),str(x['single_b_count']),str(x['union_count']),
                     str(x['pair_count']),str(len(x['pair_only_genes'])),str(len(x['single_union_only_genes']))] for x in exceptions],
                 'Table 22. All three post-result deviations from single-term gene-set union among 253 enumerated non-MoCo pairs; gene IDs are in text and results/postresult_pair_interactions.json.',
                 widths=[1.55*72,.62*72,.62*72,.52*72,.52*72,.68*72,.7*72])
    story += [P('The heme O plus protoheme edit is a pure pair-only case: neither singleton rescues '
                'a baseline-zero knockout, while the pair rescues PP_0189, PP_0744 and PP_5074. '
                'Adenosylcobalamin alone rescues 21 calls; adding FAD brings PP_0602 beyond that '
                'set. The converse case is [2Fe-2S] plus biotinyl 5-AMP: the biotinyl '
                '5-AMP singleton rescues eight gene calls, but the pair rescues zero. A fresh '
                'reload of the original and edited model for these three pairs reproduced '
                'all saved solver statuses and knockout gene sets. In the suppressive case '
                'the double-edited wild-type optimum is about 0.390006/h versus 0.586229/h '
                'for the biotinyl 5-AMP singleton. The change in optimum is a direct reason '
                'not to interpret every coefficient deletion as an independent relaxation '
                'of a fixed growth program.',BODY),
              P('This result changes the design of a transferable sensitivity audit. A simple '
                'rank of individually fragile terms would miss the heme/protoheme rescue '
                'and the six-gene MoCo pair. Conversely, summing singleton rescue counts '
                'would falsely predict eight rescues in the [2Fe-2S]/biotinyl 5-AMP pair. '
                'Reporting the exact affected gene sets, the original and edited wild-type '
                'optima, solver status, and source hash is necessary to tell a network '
                'constraint from an objective-stoichiometry interaction. It does not show '
                'molecular epistasis in cells: all edits and knockouts are in silico, '
                'the three exceptions were selected after enumeration, and matched-media '
                'phenotype data remain missing.',BODY),
              P('7.16b Reaction/GPR trace of the three exception classes',H2),
              P('The saved iJN1463 reaction and gene-rule map gives a second, model-internal way to read these exceptions, without treating model names as phenotype proof. In the heme O plus protoheme pair, the three pair-only genes PP_0189 (unlabeled in the source model), PP_0744 (hemH) and PP_5074 (hemE) are associated with PPPGO, FCLT and UPPDC1 respectively. FCLT is the model ferrochelatase reaction producing protoheme, and HEMEOS consumes protoheme to produce heme O. Neither ingredient alone removed the three zero-growth calls; removing both did. That makes an objective-coupling hypothesis plausible, but reaction adjacency by itself cannot prove which flux or dual constraint bound each knockout.',BODY),
              P('The adenosylcobalamin plus FAD pair adds one rescue, PP_0602 (ribF), to the 21 adenosylcobalamin-only calls. The source GPR attaches ribF to FMNAT and RBFK; FMNAT produces FAD in the saved reaction. This is a traceable model link between the added objective term and the extra call, not a claim that ribF is dispensable in Pseudomonas cells. Conversely, the [2Fe-2S] plus biotinyl 5-AMP pair loses all eight singleton biotinyl rescues. Its lost set includes bioB/PP_0362, which is attached to BTS5 where the saved [2Fe-2S] coefficient is negative, plus seven other gene IDs, including birA/PP_0437 attached to BACCL that produces biotinyl 5-AMP. The earlier observed wild-type optimum drop and the gene-set reversal make it unsafe to use singleton rescue sets as additive predictions.',BODY),
              P('These names and reactions are pulled from the same hashed iJN1463 snapshot as the counterfactual outcomes, and every reaction/GPR is retained in results/postresult_pair_exception_reactions.json. They are annotation, not a separate data source or mechanism validation. A causal account would require knockout-specific active flux or dual certificates, alternate-path controls and condition-matched phenotypes. This entire reaction trace was chosen after the pair results, does not change the original failed G2, and should not be counted as new wet-lab evidence.',BODY),
              P('7.16b.1 Why the suppressive pair is not a threshold artifact',H2),
              P('The eight genes lost from the singleton rescue in the [2Fe-2S] plus biotinyl 5-AMP pair have a particularly simple, falsifiable model-level interpretation. We reloaded the same hashed iJN1463 file for each of four variants and reran all eight knockout LPs while retaining the original growth-rescue threshold. Their knockout optima are zero before edits and after removing [2Fe-2S] alone; after removing biotinyl 5-AMP alone, all eight grow at about 0.586229 per hour, equal to the variant wild type. After the double edit, all eight return to numerical zero, even though the double-edited wild type remains viable at about 0.390006 per hour. Thus the disappearing rescue is not merely a failure to cross 95% of the original wild-type benchmark or a normalization choice. Every solved state was optimal and its maximum absolute mass-balance residual was below 2e-13. The source objective originally consumes both metabolites at -0.000223 per biomass unit; the individual edits have small wild-type effects but the double edit drops the maximum growth rate by one-third. These properties establish non-additive model behavior for the fixed source snapshot, not a causal intracellular pathway.',BODY),
              P('The exchange fluxes and linked reaction equations and GPRs for all four variants are retained in results/postresult_suppressive_pair_flux.json. A single optimal flux vector can move between alternate optima, so changed exchanges are not evidence that one specific route causes suppression. We did not change uptake bounds, test alternative objectives, prove a dual constraint, or measure live-cell knockout viability. The genes and pair were selected after seeing all pair results; this analysis narrows one computational ambiguity without supplying independent biological validation or changing the original G2 failure.',BODY),
              P('7.16c External-phenotype source dependence before any rescue claim',H2),
              P('The glucose-minimal-medium mutant-library study in Pseudomonas putida KT2440 (Molina-Henares et al., 2010, PMID 20158506) is a plausible condition-specific phenotype source, but it cannot be adopted as an untouched validation set by title alone. The abstract reports 48 conditionally essential knockouts, including 24 overlapping earlier in-silico proposals, and ten available mutants for proposed model-essential genes that were not essential under its tested condition. These are publication-level results, not a gene-wise check of the seven MoCo or three pair-exception calls in our model. We have not retrieved the per-gene table, matched exact media or mapped its calls to our hashed iJN1463 snapshot.',BODY),
              P('Independence is the harder issue. The full open Nogales et al. 2019 reconstruction paper explicitly compares its iJN1462 glucose-minimal gene-essentiality calls with the 2010 PRCC library: 47 predicted conditionally essential and seven predicted nonessential mutants were available for the reported 85.2% accuracy. It also evaluates glucose, acetate and p-coumarate BarSeq data, and its -2.7 fitness cutoff was checked in part against PRCC; 37 of 44 comparable conditional-essential calls agreed. The paper reports 91.3% accuracy and Matthews correlation 0.434 for the glucose BarSeq comparison. These are the results reported by the published authors, not ours. Its abstract names iJN1462, while our BiGG snapshot is named iJN1463. The live BiGG page and hashed JSON both have 1,462 genes and 2,927 reactions; an open BiGG naming issue notes this discrepancy. That is evidence of a possible alias, not proof that both snapshots are identical or independent of the published essentiality comparison. A later KT2440 RB-TnSeq compendium covers 179 conditions and notes that transposon polarity can make neighboring operon genes appear important, but its constituent assays may overlap the 2019 model comparison. The Fitness Browser June 2026 archive advertises gene-fitness data, yet exact glucose-condition rows and source-level dependence have not been audited. The publisher open copy is linked through the CSIC repository; source URLs and unresolved checks are recorded in notes/putida_phenotype_source_dependence_20260927.md. These previously used assays can at most be explicitly labeled reused-evidence contradiction checks until version lineage and assay overlap are established. We score no new phenotype here and retain the failed G2 and no-independent-validation status.',BODY),
              P('7.17 Scope and next validation',H2),



              P('The original v1 report gave 0.7225 AUROC and a 27:50 hard-call loss, which is accurate for '
                'its original eval-inclusive threshold exercise but not the end of the project. The later MoCo census '
                'adds cross-reconstruction structural scope, and the v2 OOF AUROC is approximately 0.7967, yet a '
                'repeated-label score-lineage audit limits the calibration gate. Therefore the defensible headline '
                'today is: objective-sensitivity and score-lineage audits expose model-dependent calls and evaluation limits; the '
                'later hard-call improvement is suggestive, not a clean held-out win. An independent phenotypic '
                'screen and condition-matched carbon-source evaluation remain needed for the strongest claim.',BODY)]
    return story
